name: Build AILS Filter VST3

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AILS Filter
        shell: powershell
        run: |
          cd AILS_Filter_HP
          cmake -S . -B build

      - name: Build VST3
        shell: powershell
        run: |
          cd AILS_Filter_HP
          cmake --build build --config Release

      - name: Find VST3
        shell: powershell
        run: |
          Get-ChildItem -Path AILS_Filter_HP -Recurse -Filter "*.vst3"

      - name: Upload AILS Filter VST3
        uses: actions/upload-artifact@v4
        with:
          name: AILS-Filter-HP-Windows-VST3
          path: |
            AILS_Filter_HP/build/**/*VST3/**/*.vst3
          if-no-files-found: error
